load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Writer",
    srcs = glob(["*.swift"]),
    module_name = "Writer",
    visibility = ["//visibility:public"],
)
